# Generated by Django 4.0.6 on 2022-07-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pokemon_type', models.CharField(choices=[('WA', 'WATER'), ('GR', 'GRASS'), ('GH', 'GHOST'), ('ST', 'STEEL'), ('FA', 'FAIRY')], default='WA', max_length=2)),
                ('hp', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('name_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=30, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
